name: Build Salt Packages

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: On which GitHub Environment Context To Run
      salt-version:
        type: string
        required: true
        description: The Salt version to set prior to building packages.
      dev-build:
        type: boolean
        default: false
    secrets:
      FOO:
        required: true
      SECRETS_KEY:
        required: true

jobs:
  build:
    name: Build DEB Repositories
    uses: ./.github/workflows/build-deb-repo.yml
    with:
      environment: ${{ inputs.environment }}
      salt-version: "${{ inputs.salt-version }}"
      dev-build: ${{ inputs.dev-build }}
      key-id: "37A710479D30D7B6"
    secrets:
      FOO: ${{ secrets.FOO }}
      SECRETS_KEY: ${{ secrets.SECRETS_KEY }}
