name: Nightly

on:
  push: {}
  pull_request: {}
  schedule:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
    - cron: '0 3 * * *'  # Every day at 3AM

env:
  COLUMNS: 160
  CACHE_SEED: SEED-4  # Bump the number to invalidate all caches
  RELENV_DATA: "${{ github.workspace }}/.relenv"

permissions:
  contents: read  # for dorny/paths-filter to fetch a list of changed files
  pull-requests: read  # for dorny/paths-filter to read pull requests

concurrency:
  # Concurrency is defined in a way that concurrent builds against branches do
  # not cancel previous builds.
  # However, for every new build against the same pull request source branch,
  # all older builds against that same branch get canceled.
  group: nightly-${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  build-repositories:
    name: Build Repositories
    needs:
      - ci
    uses: ./.github/workflows/build-repos.yml
    with:
      environment: nightly
      salt-version: "${{ needs.ci.outputs.salt-version }}"
      dev-build: true
    secrets:
      FOO: ${{ secrets.FOO }}
      SECRETS_KEY: ${{ secrets.SECRETS_KEY }}

  publish-repositories:
    name: Publish Repositories
    needs:
      - ci
      - build-repositories
    uses: ./.github/workflows/publish-repositories.yml
    with:
      environment: nightly
    secrets: inherit

  set-pipeline-exit-status:
    # This step is just so we can make github require this step, to pass checks
    # on a pull request instead of requiring all
    name: Set the ${{ github.workflow }} Pipeline Exit Status
    if: always()
    runs-on: ubuntu-latest
    needs:
      - ci
      - build-repositories
      - publish-repositories
    steps:
      - name: Get workflow information
        id: get-workflow-info
        uses: technote-space/workflow-conclusion-action@v3

      - name: Set Pipeline Exit Status
        shell: bash
        run: |
          if [ "${{ steps.get-workflow-info.outputs.conclusion }}" != "success" ]; then
            exit 1
          else
            exit 0
          fi

      - name: Done
        if: always()
        run:
          echo "All worflows finished"
