name: Deploy Nightly

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: On which GitHub Environment Context To Run

jobs:

  publish-repositories:
    name: Publish Reporitories
    runs-on:
      - self-hosted
      - linux
      - repo-${{ inputs.environment }}
    environment: ${{ inputs.environment }}

    steps:

      - name: Download Repository Artifact
        uses: actions/download-artifact@v3
        with:
          name: salt-${{ inputs.environment }}-repo
          path: repo/

      - name: Upload Repository Contents(${{ inputs.environment }})
        run: |
          aws s3 cp repo/* s3://salt-project-prod-salt-artifacts-${{ inputs.environment }}
